Make API_BASE_PATH, UI_BASE_PATH, UI_EXTERNAL_LOGIN_URI configurable
pulp/pulp-ui pull request #111
Opened 2024-10-18 20:38 UTC by himdel

Closes #93 

The UI builds produced by `npm run build` can be further configured by serving a `/pulp-ui-config.json` alongside the built UI. (Note it has to be mapped at `/`, not just wherever `index.html` is served from.)

* `API_BASE_PATH` - defaults to `/pulp/api/v3/` - change when using domains or a different path
* `UI_BASE_PATH` - defaults to `/ui/` - change when only serving index in a subdirectory, or want different browser path prefix
* `UI_EXTERNAL_LOGIN_URI` - defaults to nothing - set to something like `/login/` when using an SSO
* `EXTRA_VERSION` - an extra version string to display in about modal

Also documents `API_PROXY` in dev mode, and restore SSO logic when `UI_EXTERNAL_LOGIN_URI` is set.

2024-10-21 18:55 UTC, gerrod3 requested changes
This looks good. I tested it out and we will need to add a simple change to the oci-env, but other than that it works perfectly.

2024-10-21 18:55 UTC, gerrod3 commented on src/entrypoint.tsx
> +        {error}
```suggestion
        {error.toString()}
```

2024-10-21 18:55 UTC, gerrod3 commented on src/ui-config.ts
> +);
Should we add an error handle for 404? Else the error message on 404 will be JSON parse error.

2024-10-21 23:58 UTC, himdel commented
Thanks, added stringification, http error handling (I forgot `fetch` doesn't reject the promise on 404), and a fallback button to try the default config :)

![20241021235636](https://github.com/user-attachments/assets/90832cfa-67b0-4470-ad7e-beff727eb9fa)

2024-10-23 01:20 UTC, himdel commented
:crossed_fingers: 

BTW these changes also allow us to change the settings at runtime, so a runtime config UI for these is doable :) Or, say, a domain switcher that just changes UI_BASE_PATH :)

2024-10-23 01:20 UTC, merged