Add About page
pulp/pulp-ui pull request #95
Opened 2024-10-13 07:47 UTC by ZitaNemeckova

<img width="1702" alt="Screenshot 2024-10-13 at 9 42 36" src="https://github.com/user-attachments/assets/42024826-dd53-4264-ad70-be5a2d40cfd7">

Plus a small change to README for Docker users

2024-10-15 18:40 UTC, gerrod3 requested changes

2024-10-15 18:40 UTC, gerrod3 commented on src/containers/about-project.tsx
> +                  href={'https://github.com/pulp/pulp_ui/issues'}
```suggestion
                  href={'https://github.com/pulp/pulp-ui/issues'}
```

2024-10-15 18:40 UTC, gerrod3 commented on src/containers/about-project.tsx
> +                    href={'https://github.com/pulp/pulp_ui'}
```suggestion
                    href={'https://github.com/pulp/pulp-ui'}
```

2024-10-15 18:40 UTC, gerrod3 commented on src/containers/about-project.tsx
> +              <Brand style={{'display': 'block', 'margin-left': 'auto', 'margin-right': 'auto'}} src={PulpLogo} alt="PatternFly logo"/>
```suggestion
              <Brand style={{'display': 'block', 'margin-left': 'auto', 'margin-right': 'auto'}} src={PulpLogo} alt="Pulp logo"/>
```

2024-10-15 18:40 UTC, gerrod3 commented on src/containers/about-project.tsx
> +                  <CardBody>{t`This project is an attempt to up-cycle Ansible Galaxy UI codebase. The first version contains mostly saved code with minor fixes. In the future more types of content wi
```suggestion
                  <CardBody>{t`This project is an attempt to up-cycle the Ansible Galaxy UI codebase. The first version contains mostly saved code with minor fixes. In the future more types of content will be added. We welcome kindly any contributions.`}</CardBody>
```

2024-10-18 18:09 UTC, himdel commented
(needs a rebase and prettier, but LGTM :))

2024-10-18 21:07 UTC, himdel commented on src/containers/about-project.tsx
> +                      {'GitHub repository'}
```suggestion
                      {t`GitHub repository`}
```

2024-10-18 21:07 UTC, himdel commented on src/containers/about-project.tsx
> +                alt='Pulp logo'
```suggestion
                alt={t`Pulp logo`}
```

2024-10-18 21:08 UTC, himdel commented on src/containers/about-project.tsx
> +                  <CardTitle>Pulp UI</CardTitle>
```suggestion
                  <CardTitle>{APPLICATION_NAME}</CardTitle>
```

2024-10-18 21:08 UTC, himdel commented on src/containers/about-project.tsx
> +                      {'Community'}
```suggestion
                      {t`Community`}
```

2024-10-18 21:09 UTC, himdel commented on src/containers/about-project.tsx
> +                  <CardTitle>Get involved</CardTitle>
```suggestion
                  <CardTitle>{t`Get involved`}</CardTitle>
```

2024-10-18 21:09 UTC, himdel commented on src/containers/about-project.tsx
> +                  <CardTitle>Issue tracker</CardTitle>
```suggestion
                  <CardTitle>{t`Issue tracker`}</CardTitle>
```

2024-10-18 21:09 UTC, himdel commented on src/containers/about-project.tsx
> +                      {'GitHub issues'}
```suggestion
                      {t`GitHub issues`}
```

2024-10-18 21:10 UTC, himdel commented on src/containers/about-project.tsx
> +              the cloud.
```suggestion
              {t`Pulp is an open source project that makes it easy for developers to fetch, upload, and distribute Software Packages on-prem or in the cloud.`}
```

2024-10-18 21:11 UTC, himdel commented on src/containers/about-project.tsx
> +          <Card ouiaId='BasicCard'>
```suggestion
          <Card>
```

2024-10-18 21:11 UTC, himdel commented on src/containers/about-project.tsx
> +          <Card ouiaId='BasicCard'>
```suggestion
          <Card>
```

2024-10-18 21:11 UTC, himdel commented on src/containers/about-project.tsx
> +                <Card ouiaId='BasicCard'>
```suggestion
          <Card>
```

2024-10-18 21:11 UTC, himdel commented on src/containers/about-project.tsx
> +                <Card ouiaId='BasicCard'>
```suggestion
          <Card>
```

2024-10-18 21:12 UTC, himdel commented on src/containers/about-project.tsx
> +                <Card ouiaId='BasicCard'>
```suggestion
                <Card>
```

2024-10-21 22:59 UTC, merged